---
- name: update apt cache
  apt:
    update_cache: yes

- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - heaptrack
    - python3
    - python3-pip
    - zip

- name: install boto3
  ansible.builtin.pip:
    name: boto3
    state: present
