---
- name: update apt cache
  apt:
    update_cache: yes

# The retries are for random lock failures.
- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - heaptrack
    - python3
    - python3-pip
    - zip
  register: result
  until: result is succeeded
  retries: 3
  delay: 5

- name: install boto3
  ansible.builtin.pip:
    name: boto3
    state: present

- name: user for running node
  ansible.builtin.user:
    name: safe
    shell: /bin/bash
